### ISSUE TITLE
class StringIO has no attribute 'StringIO'

### ISSUE THREAD

**Issue by zzw1123** [hanzhanggit/StackGAN-v2#10]
Hi I am running the code but an error occurs:

Traceback (most recent call last):
  File "main.py", line 144, in <module>
    algo.train()
  File "/home/zzw/program/text2img/StackGAN-v2/code/trainer.py", line 755, in train
    count, self.image_dir, self.summary_writer)
  File "/home/zzw/program/text2img/StackGAN-v2/code/trainer.py", line 206, in save_img_results
    sup_real_img = summary.image('real_img', real_img_set)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/summary.py", line 179, in image
    image = make_image(tensor, height, width, channel)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/summary.py", line 186, in make_image
    output = StringIO.StringIO()
AttributeError: class StringIO has no attribute 'StringIO'

I am using python 2.7 and tensorboard1.0.0a6, and it seems like something wrong with the tensorboard version, could anybody help me?

**Comment by zhouqi4875** [comment]
I also encountered the same problem. How do you solve it in the end?

**Comment by priscillalui** [comment]
Me too! Any solutions?
