### ISSUE TITLE
EOFError, cant find a solution

### ISSUE THREAD

**Issue by vadimfedulov256** [hanzhanggit/StackGAN-v2#16]
Traceback (most recent call last):
  File "main.py", line 150, in <module>
    algo.train()
  File "/disk/StackGAN-v2-master/code/trainer.py", line 347, in train
    self.inception_model, start_count = load_network(self.gpus)
  File "/disk/StackGAN-v2-master/code/trainer.py", line 132, in load_network
    state_dict = torch.load(cfg.TRAIN.NET_G)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 531, in _load
    magic_number = pickle_module.load(f)
EOFError

**Comment by vadimfedulov256** [comment]
Okay, netG model was actually empy, but there was a written way to it, so I have solved this problem.
